apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}-storage-service
spec:
  ports:
  - protocol: {{ .Values.storage.service.protocol | default "TCP" }}
    port: {{ .Values.storage.service.port }}
    targetPort: {{ .Values.storage.service.targetPort }}
    name: storage
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-storage
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-storage
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-storage
        app.kubernetes.io/name: {{ .Release.Name }}-storage
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.storage.container.image }}
          name: {{ .Release.Name }}-storage
          args:
            - serve
          ports:
          - name: storage
            containerPort: {{ .Values.storage.service.targetPort }}
            protocol: {{ .Values.storage.service.protocol | default "TCP" }}
          env:
            - name: BIND
              value: {{ .Values.storage.env.BIND | quote }}
            - name: HASURA_ENDPOINT
              value: http://{{ .Release.Name }}-hasura-service:{{ .Values.hasura.service.port }}/v1
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              value: {{ .Values.hasura.env.HASURA_GRAPHQL_ADMIN_SECRET | quote }}
            - name: HASURA_METADATA
              value: {{ .Values.storage.env.HASURA_METADATA | quote }}
            - name: POSTGRES_MIGRATIONS
              value: {{ .Values.storage.env.POSTGRES_MIGRATIONS | quote }}
            - name: POSTGRES_MIGRATIONS_SOURCE
              value: "postgres://{{ .Values.postgres.env.POSTGRES_USER }}:{{ .Values.postgres.env.POSTGRES_PASSWORD }}@{{ .Release.Name }}-postgres-service:{{ .Values.postgres.service.targetPort }}/{{ .Values.postgres.env.POSTGRES_DB | default .Release.Name }}?sslmode=disable"
            - name: PUBLIC_URL
              value: "https://{{ .Release.Name }}.storage.{{ .Values.domain }}"
            - name: S3_ACCESS_KEY
              value: {{ .Values.minio.env.MINIO_ROOT_PASSWORD | quote }}
            - name: S3_BUCKET
              value: {{ .Values.storage.env.S3_BUCKET | quote }}
            - name: S3_ENDPOINT
              value: http://{{ .Release.Name }}-minio-service:{{ .Values.minio.container.minio_port }}
            - name: S3_REGION
              value: {{ .Values.storage.env.S3_REGION | quote }}
            - name: S3_ROOT_FOLDER
              value: {{ .Values.storage.env.S3_ROOT_FOLDER | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.minio.env.MINIO_ROOT_PASSWORD | quote }}
          
          resources: {}
      restartPolicy: Always
status: {}
