apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-storage-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules: 
    - host: {{ .Release.Name }}.storage.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-storage-service
                port:
                  number: {{ .Values.storage.service.port }}
  tls:
    - secretName: nhost-test-storage-tls
      hosts:
        - {{ .Release.Name }}.{{ .Values.domain }}