domain: "example.com"
git: 
  repo: "github.com/suplere/selfhost-app-test.git"
  # path to NHOST project in git repository
  path: "/packages/nhost-backend"
  # if not provided this is public repository, secret must have username and password or key as password
  private: false
  secretName: "" 
    

app:
  env:

postgres:
  service: 
    protocol: "TCP"
    port: 5432
    targetPort: 5432
  persistent:
    class: "longhorn"
    size: "1Gi"
  container:
    image: "postgres:14-alpine"  
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres" 
    POSTGRES_DB: ""

minio:
  persistent:
    class: "longhorn"
    size: "1Gi"
  container:
    image: "minio/minio:RELEASE.2022-07-08T00-05-23Z"  
    minio_port: 9000
    console_port: 9001
  env:
    MINIO_ROOT_PASSWORD: "minioaccesskey123123"
    MINIO_ROOT_USER: "minioaccesskey123123" 
    
hasura:
  service: 
    protocol: "TCP"
    port: 80
    targetPort: 8080
  container:
    tag: "v2.29.0-ce"
    image: "hasura/graphql-engine:v2.29.0-ce" 
  env:
    HASURA_GRAPHQL_ENABLE_CONSOLE: true
    # enable debugging mode. It is recommended to disable this in production
    HASURA_GRAPHQL_DEV_MODE: "true"
    HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
    HASURA_GRAPHQL_ADMIN_SECRET: "nhost-admin-secret"
    HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
    HASURA_GRAPHQL_CORS_DOMAIN: "*"
    HASURA_GRAPHQL_DISABLE_CORS: "false"
    HASURA_GRAPHQL_ENABLED_APIS: "metadata,graphql,pgdump,config"
    HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup,http-log,webhook-log,websocket-log"
    HASURA_GRAPHQL_ENABLE_ALLOWLIST: "false"
    HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "false"
    HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    HASURA_GRAPHQL_EVENTS_HTTP_POOL_SIZE: "100"
    HASURA_GRAPHQL_JWT_SECRET_KEY: "secretkey"
    HASURA_GRAPHQL_JWT_SECRET_TYPE: "HS256"
    HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_BATCH_SIZE: "100"
    HASURA_GRAPHQL_LIVE_QUERIES_MULTIPLEXED_REFETCH_INTERVAL: "1000"
    HASURA_GRAPHQL_LOG_LEVEL: "warn"
    HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES: "false"
    HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "public"
    HASURA_GRAPHQL_WS_READ_COOKIE: "false"
    NHOST_WEBHOOK_SECRET: "nhost-webhook-secret" 

storage:
  service: 
    protocol: "TCP"
    port: 5000
    targetPort: 5000
  container:
    image: "nhost/hasura-storage:0.3.5" 
  env:
    BIND: ":5000"
    HASURA_METADATA: "1"
    POSTGRES_MIGRATIONS: "1"
    S3_BUCKET: "nhost"
    S3_REGION: ""
    S3_ROOT_FOLDER: ""

auth: 
  service: 
    protocol: "TCP"
    port: 4000
    targetPort: 4000
  container:
    image: "nhost/hasura-auth:0.21.3"
  smtp: 
    AUTH_SMTP_AUTH_METHOD: "LOGIN"
    AUTH_SMTP_HOST: "mailhog"
    AUTH_SMTP_PASS: "password"
    AUTH_SMTP_PORT: "1025"
    AUTH_SMTP_SECURE: "false"
    AUTH_SMTP_SENDER: "hasura-auth@example.com"
    AUTH_SMTP_USER: "user"
  env:
    AUTH_ACCESS_CONTROL_ALLOWED_EMAIL_DOMAINS: ""
    AUTH_ACCESS_CONTROL_ALLOWED_EMAILS: ""
    AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS: ""
    AUTH_ACCESS_CONTROL_BLOCKED_EMAIL_DOMAINS: ""
    AUTH_ACCESS_CONTROL_BLOCKED_EMAILS: ""
    AUTH_ACCESS_TOKEN_EXPIRES_IN: "900"
    AUTH_ANONYMOUS_USERS_ENABLED: "false"
    AUTH_CLIENT_URL: http://localhost:3000
    AUTH_DISABLE_NEW_USERS: "false"
    AUTH_EMAIL_PASSWORDLESS_ENABLED: "true"
    AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED: "false"
    AUTH_GRAVATAR_DEFAULT: blank
    AUTH_GRAVATAR_ENABLED: "true"
    AUTH_GRAVATAR_RATING: g
    AUTH_HOST: 0.0.0.0
    AUTH_JWT_CUSTOM_CLAIMS: '{}'
    AUTH_LOCALE_ALLOWED_LOCALES: en,cs
    AUTH_LOCALE_DEFAULT: cs
    AUTH_MFA_ENABLED: "false"
    AUTH_MFA_TOTP_ISSUER: ""
    AUTH_PASSWORD_HIBP_ENABLED: "false"
    AUTH_PASSWORD_MIN_LENGTH: "9"
    AUTH_PROVIDER_GOOGLE_CLIENT_ID: client_id
    AUTH_PROVIDER_GOOGLE_CLIENT_SECRET: client_secret
    AUTH_PROVIDER_GOOGLE_ENABLED: "true"
    AUTH_PROVIDER_GOOGLE_SCOPE: ""
    AUTH_REFRESH_TOKEN_EXPIRES_IN: "43200"
    AUTH_SMTP_AUTH_METHOD: LOGIN
    AUTH_USER_DEFAULT_ALLOWED_ROLES: user,me
    AUTH_USER_DEFAULT_ROLE: user
    AUTH_WEBAUTHN_ATTESTATION_TIMEOUT: "60000"
    AUTH_WEBAUTHN_ENABLED: "true"
    AUTH_WEBAUTHN_RP_NAME: nextjs-server-components
    AUTH_WEBAUTHN_RP_ORIGINS: http://localhost:3000

mailhog: 
  enabled: true
  service: 
    protocol: "TCP"
    port: 8025
    targetPort: 8025
  container:
    image: "jcalonso/mailhog:v1.0.1"
  env:
    SMTP_HOST: "mailhog"
    SMTP_PASS: "password"
    SMTP_PORT: "1025"
    SMTP_SECURE: "false"
    SMTP_SENDER: "hasura-auth@example.com"
    SMTP_USER: "user"  

functions:
  service: 
    protocol: "TCP"
    port: 3000
    targetPort: 3000
  container:
    image: "nhost/functions:1.0.0" 
  env:

dashboard:
  enabled: true
  ingress: 
    enabled: false
  service: 
    protocol: "TCP"
    port: 7000
    targetPort: 3000
  container:
    image: "nhost/dashboard:0.20.20" 
  env: